---
title: "Untitled"
author: "Jason Freels"
date: "9/15/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overall comments

With the exception of a few phrasing issues - some of which I highlight below - the paper is well written. With that said this paper has some significant issues that must be addressed.  The first, and most significant issue is that the authors do not clearly highlight the novel contribution made by this paper.  While I have researched complex modifications of the Weibull model such as , I have little experience with sectional models. From a limited reading about sectional models to suport this review, it seems that there is a novel contribution here - but it needs to be highlighted more clearly. This issue is exacerbated by a lengthy review of the application of maximum likelihood estimation to many different types of reliability data.  Much of this review offers little to help the reader understand the purpose of the paper.  The authors should focus this introductory review more narrrowly to help the reader understand how this work adds to the current body of literature.  The second significant issue is that the authors only implement their method on a single data set.  The authors should include add another data set in their paper

## Specific comments

Please change all mentions of "maximum likelihood function" to "likelihood function"

There are several instances where the author refer to failures as "samples" - this is quite distracting and should explained more clearly.

### Page 2

"Develop and implement an algorithm based on the NR method capable of assisting the numerical solution"

- What does "assisting the numerical solution" mean here?

### Page 4

"In this paper, the estimate made by WPP will be used as the initial value in the numerical solution of the expressions resulting from the maximum likelihood function."

- Are you referring to the parameter estimates here?

"MLE for Type-I right censored data, with ğ‘Ÿ samples observed in relation to a total of ğ‘› samples"

- This should readğ‘Ÿfailures observed in relation to a total of ğ‘› samples


"In the case of WS2P3P, in addition to ğ‘Ÿ and ğ‘›, it is necessary to consider the number of samples $i_s$ observed..."

- This should be "the number of failures $i_s$ observed..."

### Page 6

The matrix displayed in (48) is the Hessian matrix, not the Jacobian - this should be updated along with other references to this matrix in the paper. 


### Page 7

"The data was obtained from around 180 vehicles recording a total of around one million miles over just over a year of use around the world [50]."

- This should read "The data were obtained from 180 vehicles operating a total of one million miles over one year of use around the world [50]."
